/*
 * This source file was generated by the Gradle 'init' task
 */
package org.imlcalculator;

import org.imlcalculator.view.Window;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Window window = new Window();
        window.setVisible(true);
    }
}
